### ISSUE TITLE
Establish complete list of Interest & Task Groups

### ISSUE THREAD

**Issue by CynthiaParr-USDA** [tdwg/infrastructure#18]
- [x] finish the task of porting charters of IG and TGs from old site into Typo3 pages
- [ ] add new IGs and Task groups (what are they where are their charters?)
- [ ] Add column linking to the most recent report with the date of late
- [ ] Add column for convener(s)?
- [ ] Need to make tickets for each group that needs it

**Comment by CynthiaParr-USDA** [comment]
From: http://tdwgng.tdwg.org/activities/ list of activities to port. Check box when main description page is ported, make new tickets for other links/content need work (e.g. wiki)
- [x] Biological Descriptions Interest Group  
- [x] GIG   Geospatial Interest Group  
- [x] IMG   Imaging Interest Group  
- [x]   MRTG       Multimedia Resources Task Group  
- [x] ISIG  Invasive Species Interest Group 
- [x] LIT   Literature Interest Group   Interest Group  
- [x] NCD   Natural Collections Descriptions Interest Group Interest Group  
- [x] OSR   Observation and Specimen Records    Interest Group  
  - [x] ABCD    Access to Biological Collections Data    Task Group
  - [x]  DwC    DarwinCore Task Group (DwC)  
  - [x] OBS     Observations Task Group (OBS)  
- [x] Phylo Phylogenetics Interest Group  
- [x] Process   Process Interest Group  
- [x] TNC   Taxonomic Names and Concepts Interest Group 
- [x] TAG   TDWG Architecture Group Interest Group  
- [x]   GUID       Globally Unique Identifiers  Task Group
  - [x]  TAPIR      TAPIR Task Group
- [x] TIP   TDWG Infrastructure Project

**Comment by CynthiaParr-USDA** [comment]
New groups to add:
- [x] Annotations IG
- [ ] Vocab Maintenance Spec  TG https://github.com/tdwg/infrastructure/issues/42
- [ ] Species information IG https://github.com/tdwg/exec/issues/10
- [ ] Biodviersity services and Clients IG https://github.com/tdwg/exec/issues/9 -- needs wiki/mailing list links
- [x] IG Data quality with
- [x] TG1 - Framework (Allan Koch Veiga)
- [x] TG2 - Tools, services and workflows (Lee Belbin)
- [x] TG3 - Case studies (Miles Nicholls - ALA)
  @pmergen (or anybody) any others?

**Comment by CynthiaParr-USDA** [comment]
- [ ] TAPIR is a task group so should appear nested in an interest group?

**Comment by pmergen** [comment]
I am getting confused on how to follow this up ?  I had started to create an issue per IG or TG under infrastructure so I can see and follow what there is to do, still to do for each group and have the people concerned help out.  now there is also this list and the issues on the IGs are all over the place in infrastructure ? There is a Github issue where this work to check all the iG and coordinate with the chairs is assigned to me and this which is assigned to Cyndy and it goes to doubling of efforts. If I should continue this I would like a separate repository (which I created and called "IG-and-TG-follow-op-on-Website" to be directly under TDWG/ and not under Infrastructure mixed with all sorts of other issues and that all the issues related to this in infrastructure are moved to this repository. 
I played with the Git hub interface and functions, but could not see how to move an issue from one repository to another or add a tag so it shows there too. 

Can someone advice here on how to move issues in another repository ?

Thanks

**Comment by CynthiaParr-USDA** [comment]
this ticket summarizes. the other tickets are for each group. stan offered to help, i should have reassigned tickets. we should avoid creating another repository, I don't mind having them all in infrastructure.

**Comment by CynthiaParr-USDA** [comment]
Also, please not that I am assigned to this ticket because it is my job to make sure no group is left out of t the website.  I am not contacting any conveners -- that's your ticket.  I am also not volunteering to make all these pages. I'm just coordinating.  In my opinion, if there is no additional work needed for a group you don't need to make a ticket for it.

**Comment by peterdesmet** [comment]
@pmergen, you cannot move issues from one repository to the next. What I would do is create a **milestone** in this `infrastructure` repository (as it is related to infrastructure) to group all issues related to `IG/TG`. That way it's easier to see and follow up all issues related to that task, since milestones always indicate how far you are from finishing it. Here are the current milestone in infrastructure: https://github.com/tdwg/infrastructure/milestones

I have created a milestone already and grouped all issues with the label `IG/TG`: https://github.com/tdwg/infrastructure/milestones/IG/TG%20on%20website.

You can rename, add, throw out as you please. You can assign a milestone for each issue on the right hand side (under `labels`) or for multiple issues at once in the issues overview, by clicking the checkbox and selecting a milestone.

More information on creating milestones (and managing GitHub issues in general) can be found at https://guides.github.com/features/issues/ (useful read!)

I have removed the https://github.com/tdwg/IG-and-TG-follow-op-on-Website repository to keep things tidy.

**Comment by pmergen** [comment]
There is an additional IG with 3 TG which does not appear in your check list 
IG Data quality 
with 3 TG 
TG1 - Framework (Allan Koch Veiga)
TG2 - Tools, services and workflows (Lee Belbin)
TG3 - Case studies (Miles Nicholls - ALA)

it is for now on the GBIF community site where it was waiting to have the TDWG new site ready. http://community.gbif.org/pg/groups/21292/gbiftdwg-biodiversity-data-quality-interest-group/ 
it is lablled TDWG/GBIF.

thus also to be on the list of groups of TDWG, I remember that several years ago TDWG approved them, but  was put there at the GBIF as the TDWG site was not available to put new groups charters in.

**Comment by CynthiaParr-USDA** [comment]
Thanks -- exactly what we needed. I will add to the checklist, but I don't have time right now to make tickets to follow up on each of these.

**Comment by pmergen** [comment]
it is fine for the DQ IG I made one ticket for now which includes also the 3 TG. I will see later depending on Arthur's report if i have to have 4 issues here one for the IG and one each for each TG. Suggest to wait until we have more info from the different conveners.
